#pragma region 资源定义
#define IDC_MYICON                      2
#define IDD_DEMO_DIALOG                 102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_DEMO                        107
#define IDI_SMALL                       108
#define IDC_DEMO                        109
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_START                135
#define IDB_BITMAP_ROCK                 137
#define IDB_BITMAP_BRICK                138
#define IDB_BITMAP_HELP                 145
#define IDB_BITMAP_JINGDIAN             146
#define IDB_BITMAP_KUANGBAO             147
#define IDB_BITMAP_TITLE                148
#define IDB_BITMAP_BACKGROUND           149
#define IDB_BITMAP_OPEN                 150
#define IDB_BITMAP_STUDY                151
#define IDB_BITMAP_TITLES               152
#define IDB_BITMAP__START               153
#define IDB_BITMAP__HELP                154
#define IDB_BITMAP_BACKGROUND2          155
#define IDB_BITMAP_BACK                 156
#define IDB_BITMAP_shuoming             157
#define IDB_BITMAP_CONTINUE             158
#define IDB_BITMAP_RESTART              159
#define IDB_BITMAP_BACKTO               160
#define IDB_BITMAP_END                  161
#define IDB_BITMAP_EXPLAIN              162
#define IDB_BITMAP_SHEZHI               163
#define IDB_BITMAP_SLOW                 164
#define IDB_BITMAP_MEDIUM               165
#define IDB_BITMAP_FAST                 166
#define IDB_BITMAP_1                    167
#define IDB_BITMAP_10                   168
#define IDB_BITMAP_TEN                  169
#define IDB_BITMAP_100                  170
#define IDB_BITMAP_EXPLAINED            171
#define IDB_BITMAP_BACKGROUND3          172
#define IDB_BITMAP_BACKGROUND4          173
#define IDB_BITMAP_CHALLENGE            174
#define IDB_BITMAP_PERFECT              175
#define IDB_BITMAP_GREAT                176
#define IDB_BITMAP_REGRETFUL            177
#define IDB_BITMAP_6                    178
#define IDB_BITMAP_666                  179
#define IDB_BITMAP_FAIL                 180
#define IDB_BITMAP_GIFT                 181
#define IDB_BITMAP_fubao                182
#define IDB_PNG1                        183
#define IDB_BITMAP_BARRIER              184
#define IDB_BITMAP1                     185
#define IDB_BITMAP_RROCK                185
#define IDB_BITMAP2                     186
#define IDB_BITMAP_TOHELP               186
#define IDC_STATIC                      -1
